name: Build and Deploy Frontend
on:
  push:
    branches:
      - main # Change this if your main branch has a different name

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v6

      - name: ⚙️ Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: 🔨 Install dependencies
        run: npm install

      - name: 🏗️ Build Project
        run: npm run build

      - name: 📂 Sync Files to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: /public_html/
          # Fix for cPanel ECONNRESET (Switching to FTPS Legacy with Loose Security)
          protocol: ftps-legacy
          security: loose
